
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# Driver for the control of 8 switch board
#
# Author:   Luca Rosignoli
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
#
# import RPi.GPIO as GPIO
from logging import Logger


class SwitchDevice:

    def __init__(self, logger: Logger):
        self.name: str = 'device'
        self.logger = Logger

        # Device properties
        self._maxswitch: int = 8
        self._canwrite: bool = True
        self._minswitchvalue: int = 0
        self._maxswitchvalue: int = 1
        self._switchstep: int = 1

        # Device variables
        self._switchpinout: dict = {'s1': 18,
                                    's2': 23,
                                    's3': 24,
                                    's4': 25,
                                    's5': 8,
                                    's6': 7,
                                    's7': 12,
                                    's8': 16}
        
        self._switchdescription: dict = {'s1': 'Roof power',
                                         's2': 'Weather sensor power',
                                         's3': 'Mount power',
                                         's4': 'Camera power',
                                         's5': 'Astro Pc power',
                                         's6': 'Security power',
                                         's7': 'Light power',
                                         's8': 'Flatbox power'}
        
        self._switchname: dict = {'s1': 'Roof',
                                  's2': 'Weather sensor',
                                  's3': 'Mount',
                                  's4': 'Camera',
                                  's5': 'Astro Pc',
                                  's6': 'Security',
                                  's7': 'Light',
                                  's8': 'Flatbox'}

        self._switchstate: dict = {'s1': False,
                                   's2': False,
                                   's3': False,
                                   's4': False,
                                   's5': False,
                                   's6': False,
                                   's7': False,
                                   's8': False}
        
        self._connected: bool = False

        #
        # Guarded properties
        #
        @property
        def maxswitch(self) -> int:
            res = self._maxswitch
            return res
        
        @property
        def canwrite(self) -> bool:
            res = self._canwrite
            return res
        
        @property
        def minswitchvalue(self) -> int:
            res = self._minswitchvalue
            return res
        
        @property
        def maxswitchvalue(self) -> int:
            res = self._maxswitchvalue
            return res
        
        @property
        def switchstep(self) -> int:
            res = self._switchstep
            return res
        
        @property
        def switchdescription(self, key) -> str:
            res = self._switchdescription[key]
            return res
        
        @property
        def switchname(self, key) -> str:
            res = self._switchname[key]
            return res
        
        @property
        def connected(self) -> bool:
            res = self._connected
            return res
        
        @property.setter
        def connected(self, connected: bool):
            self._connected = connected
            self.logger.info(f'Device connection: {connected}')
            """ Put here the initialization of the pinouts and
            give some warning if you want disconnect when some
            switch are close"""
        
        @property
        def switchstate(self, key) -> bool:
            res = self._switchstate[key]
            return res
        
        @property.setter
        def switchstate(self, key, state):
            self._switchstate[key] = state
            self.logger.info(f'Switch {key}: {state}')
            """Put here some warnings if you want to put a switch in
            a state in which it is already"""

    
    
