
# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# Driver for the control of 8 switch board
#
# Author:   Luca Rosignoli
#
# -----------------------------------------------------------------------------
# Edit History:
#   Generated by Python Interface Generator for AlpycaDevice
#
#
# import RPi.GPIO as GPIO

from logging import Logger

class SwitchDevice:

    def __init__(self, logger: Logger):
        self.name: str = 'SwitchDevice'
        self.logger = Logger

        # Device properties
        self._maxswitch: int = 8
        self._canwrite: bool = True
        self._minswitchvalue: int = 0
        self._maxswitchvalue: int = 1
        self._switchstep: int = 1

        # Device variables
        self._switchpinout: dict = {'s1': 18,
                                    's2': 23,
                                    's3': 24,
                                    's4': 25,
                                    's5': 8,
                                    's6': 7,
                                    's7': 12,
                                    's8': 16}
        
        self._switchdescription: dict = {'s1': 'Roof power',
                                         's2': 'Weather sensor power',
                                         's3': 'Mount power',
                                         's4': 'Camera power',
                                         's5': 'Astro Pc power',
                                         's6': 'Security power',
                                         's7': 'Light power',
                                         's8': 'Flatbox power'}
        
        self._switchname: dict = {'s1': 'Roof',
                                  's2': 'Weather sensor',
                                  's3': 'Mount',
                                  's4': 'Camera',
                                  's5': 'Astro Pc',
                                  's6': 'Security',
                                  's7': 'Light',
                                  's8': 'Flatbox'}
        

        self._switchstate: dict = {'s1': False,
                                   's2': False,
                                   's3': False,
                                   's4': False,
                                   's5': False,
                                   's6': False,
                                   's7': False,
                                   's8': False}
        
        self._connected: bool = False


    #
    # Guarded properties
    #
    @property
    def maxswitch(self) -> int:
        res = self._maxswitch
        return res
    
    @property
    def connected(self) -> bool:
        res = self._connected
        return res
    
    @connected.setter
    def connected(self, connected: bool):
        self._connected = connected
    
    #    
    # GET, SET METHOD (need more than self parameter)
    #

    def get_minswitchvalue(self, key) -> int:
        res = self._minswitchvalue
        return res
    
    def get_maxswitchvalue(self, key) -> int:
        res = self._maxswitchvalue
        return res
    
    def get_switchstep(self, key) -> int:
        res = self._switchstep
        return res
    
    def get_canwrite(self, key) -> bool:
        res = self._canwrite
        return res
    
    def get_switchdescription(self, key) -> str:
        res = self._switchdescription[list(self._switchdescription)[key]]
        return res
    
    def get_switchname(self, key) -> str:
        res = self._switchname[list(self._switchname)[key]]
        return res
    
    def set_switchname(self, key, name):
        self._switchname[list(self._switchname)[key]] = name
    
    
    def get_switchstate(self, key) -> bool:
        res = self._switchstate[list(self._switchstate)[key]]
        return res
    
    def set_switchstate(self, key, state):
        self._switchstate[list(self._switchstate)[key]] = state
        
    
    def get_switchvalue(self, key) -> int:
        res = int(self._switchstate[list(self._switchstate)[key]])
        return res
    

    def set_switchvalue(self, key, value):
        self._switchstate[list(self._switchstate)[key]] = bool(value)
        

        
